apiVersion: apps/v1
kind: Deployment
metadata:
  name: umsdeployement
  labels:
    app: usermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
      - name: usermanagement
        image: usermanagementregistry.azurecr.io/userrepository:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: mysecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagementsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: usermanagement